added first draft of donation post feed and function to get donation …
ysheliakin/demeter pull request #30
Opened 2024-04-07 23:16 UTC by mertdayi01

…post data

2024-04-09 00:03 UTC, ysheliakin requested changes
I think this a good start with some minor things to correct

2024-04-22 02:08 UTC, mertdayi01 commented on views/pages/index.html
> +        {{template "donationPostFeed" .}}
ok i removed it.

2024-04-22 02:10 UTC, mertdayi01 commented on main.go
> +	e.GET("/donationPostFeed", func(c echo.Context) error {
sounds good. changed it to feed

2024-04-22 02:11 UTC, mertdayi01 commented on main.go
> +	e.POST("/donationPostFeed", func(c echo.Context) error {
i wasn't exactly sure what it was doing so i added it. ill try removing it.

2024-04-22 02:40 UTC, mertdayi01 commented on db/queries/donation.sql
> +SELECT * FROM donations;
i'm not sure what else to do.

2024-04-22 02:42 UTC, mertdayi01 commented on views/components/donationPostFeed.html
moved it

2024-04-23 20:42 UTC, ysheliakin approved these changes

2024-04-23 20:42 UTC, merged